// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExpensesColumns holds the columns for the "expenses" table.
	ExpensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "paid_by", Type: field.TypeUUID},
		{Name: "shares", Type: field.TypeJSON},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"GROCERIES", "OTHER"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "cost", Type: field.TypeString},
		{Name: "receipt_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// ExpensesTable holds the schema information for the "expenses" table.
	ExpensesTable = &schema.Table{
		Name:       "expenses",
		Columns:    ExpensesColumns,
		PrimaryKey: []*schema.Column{ExpensesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// ExpenseDebtorsColumns holds the columns for the "expense_debtors" table.
	ExpenseDebtorsColumns = []*schema.Column{
		{Name: "expense_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ExpenseDebtorsTable holds the schema information for the "expense_debtors" table.
	ExpenseDebtorsTable = &schema.Table{
		Name:       "expense_debtors",
		Columns:    ExpenseDebtorsColumns,
		PrimaryKey: []*schema.Column{ExpenseDebtorsColumns[0], ExpenseDebtorsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "expense_debtors_expense_id",
				Columns:    []*schema.Column{ExpenseDebtorsColumns[0]},
				RefColumns: []*schema.Column{ExpensesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "expense_debtors_user_id",
				Columns:    []*schema.Column{ExpenseDebtorsColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExpensesTable,
		UsersTable,
		ExpenseDebtorsTable,
	}
)

func init() {
	ExpenseDebtorsTable.ForeignKeys[0].RefTable = ExpensesTable
	ExpenseDebtorsTable.ForeignKeys[1].RefTable = UsersTable
}
