// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExpensesColumns holds the columns for the "expenses" table.
	ExpensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "shares", Type: field.TypeJSON},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"GROCERIES", "OTHER"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "cost", Type: field.TypeString},
		{Name: "receipt_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "user_expenses", Type: field.TypeInt},
	}
	// ExpensesTable holds the schema information for the "expenses" table.
	ExpensesTable = &schema.Table{
		Name:       "expenses",
		Columns:    ExpensesColumns,
		PrimaryKey: []*schema.Column{ExpensesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "expenses_users_expenses",
				Columns:    []*schema.Column{ExpensesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expense_debtors", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_expenses_debtors",
				Columns:    []*schema.Column{UsersColumns[5]},
				RefColumns: []*schema.Column{ExpensesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExpensesTable,
		UsersTable,
	}
)

func init() {
	ExpensesTable.ForeignKeys[0].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = ExpensesTable
}
